High: build: add lib/stonith/sbd.h to distribution tar ball
sbd.h is needed to build sdb STONITH

[snip]
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../include -I../../include -I../../include -I../../linux-ha -I../../linux-ha -I../../libltdl -I../../libltdl  -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -I/usr/include/libxml2 -D_GNU_SOURCE -g -O2  -Wall -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wdeclaration-after-statement -Wpointer-arith -Wwrite-strings -Wcast-qual -Wcast-align -Wbad-function-cast -Winline -Wmissing-format-attribute -Wformat=2 -Wformat-security -Wformat-nonliteral -Wno-long-long -Wno-strict-aliasing   -ggdb3 -funsigned-char -MT sbd-sbd.o -MD -MP -MF .deps/sbd-sbd.Tpo -c -o sbd-sbd.o `test -f 'sbd.c' || echo './'`sbd.c
sbd.c:38:17: error: sbd.h: No such file or directory
sbd.c:64: warning: function declaration isn't a prototype
sbd.c: In function 'cmd2char':
sbd.c:184: error: 'SBD_MSG_EMPTY' undeclared (first use in this function)
sbd.c:184: error: (Each undeclared identifier is reported only once
sbd.c:184: error: for each function it appears in.)
sbd.c:186: error: 'SBD_MSG_TEST' undeclared (first use in this function)
sbd.c:188: error: 'SBD_MSG_RESET' undeclared (first use in this function)
sbd.c:190: error: 'SBD_MSG_OFF' undeclared (first use in this function)
sbd.c:192: error: 'SBD_MSG_EXIT' undeclared (first use in this function)
sbd.c: At top level:
sbd.c:199: warning: no previous prototype for 'sector_alloc'
sbd.c: In function 'char2cmd':
sbd.c:215: error: 'SBD_MSG_EMPTY' undeclared (first use in this function)
sbd.c:218: error: 'SBD_MSG_TEST' undeclared (first use in this function)
sbd.c:221: error: 'SBD_MSG_RESET' undeclared (first use in this function)
sbd.c:224: error: 'SBD_MSG_OFF' undeclared (first use in this function)
sbd.c:227: error: 'SBD_MSG_EXIT' undeclared (first use in this function)
sbd.c: At top level:
sbd.c:267: warning: 'struct sector_node_s' declared inside parameter list
sbd.c:267: warning: its scope is only this definition or declaration, which is probably not what you want
sbd.c: In function 'slot_read':
sbd.c:269: warning: implicit declaration of function 'SLOT_TO_SECTOR'
sbd.c: At top level:
sbd.c:273: warning: 'struct sector_node_s' declared inside parameter list
sbd.c:279: warning: 'struct sector_mbox_s' declared inside parameter list
sbd.c: In function 'mbox_write':
sbd.c:281: warning: implicit declaration of function 'MBOX_TO_SECTOR'
sbd.c: At top level:
sbd.c:285: warning: 'struct sector_mbox_s' declared inside parameter list
sbd.c:291: warning: 'struct sector_mbox_s' declared inside parameter list
sbd.c:311: warning: 'struct sector_header_s' declared inside parameter list
sbd.c: In function 'header_write':
sbd.c:313: error: dereferencing pointer to incomplete type
sbd.c:313: warning: implicit declaration of function 'htonl'
sbd.c:313: error: dereferencing pointer to incomplete type
sbd.c:314: error: dereferencing pointer to incomplete type
sbd.c:314: error: dereferencing pointer to incomplete type
sbd.c:315: error: dereferencing pointer to incomplete type
sbd.c:315: error: dereferencing pointer to incomplete type
sbd.c:316: error: dereferencing pointer to incomplete type
sbd.c:316: error: dereferencing pointer to incomplete type
sbd.c:317: error: dereferencing pointer to incomplete type
sbd.c:317: error: dereferencing pointer to incomplete type
sbd.c: At top level:
sbd.c:322: warning: 'struct sector_header_s' declared inside parameter list
sbd.c: In function 'header_read':
sbd.c:327: error: dereferencing pointer to incomplete type
sbd.c:327: warning: implicit declaration of function 'ntohl'
sbd.c:327: error: dereferencing pointer to incomplete type
sbd.c:328: error: dereferencing pointer to incomplete type
sbd.c:328: error: dereferencing pointer to incomplete type
sbd.c:329: error: dereferencing pointer to incomplete type
sbd.c:329: error: dereferencing pointer to incomplete type
sbd.c:330: error: dereferencing pointer to incomplete type
sbd.c:330: error: dereferencing pointer to incomplete type
sbd.c:331: error: dereferencing pointer to incomplete type
sbd.c:331: error: dereferencing pointer to incomplete type
sbd.c:333: error: dereferencing pointer to incomplete type
sbd.c:334: error: dereferencing pointer to incomplete type
sbd.c:335: error: dereferencing pointer to incomplete type
sbd.c:336: error: dereferencing pointer to incomplete type
sbd.c: At top level:
sbd.c:342: warning: 'struct sector_header_s' declared inside parameter list
sbd.c: In function 'valid_header':
sbd.c:344: error: dereferencing pointer to incomplete type
sbd.c:344: error: dereferencing pointer to incomplete type
sbd.c:348: error: dereferencing pointer to incomplete type
sbd.c:352: error: dereferencing pointer to incomplete type
sbd.c: In function 'header_get':
sbd.c:365: warning: passing argument 1 of 'header_read' from incompatible pointer type
sbd.c:370: warning: passing argument 1 of 'valid_header' from incompatible pointer type
sbd.c: In function 'init_device':
sbd.c:394: error: dereferencing pointer to incomplete type
sbd.c:394: error: dereferencing pointer to incomplete type
sbd.c:395: error: dereferencing pointer to incomplete type
sbd.c:396: error: dereferencing pointer to incomplete type
sbd.c:397: error: dereferencing pointer to incomplete type
sbd.c:398: error: dereferencing pointer to incomplete type
sbd.c:399: error: dereferencing pointer to incomplete type
sbd.c:400: error: dereferencing pointer to incomplete type
sbd.c:401: error: dereferencing pointer to incomplete type
sbd.c:408: error: dereferencing pointer to incomplete type
sbd.c:410: warning: passing argument 1 of 'header_write' from incompatible pointer type
sbd.c:414: error: dereferencing pointer to incomplete type
sbd.c:416: error: dereferencing pointer to incomplete type
sbd.c:417: warning: passing argument 2 of 'slot_write' from incompatible pointer type
sbd.c:420: warning: passing argument 2 of 'mbox_write' from incompatible pointer type
sbd.c: In function 'slot_lookup':
sbd.c:448: error: dereferencing pointer to incomplete type
sbd.c:449: warning: passing argument 2 of 'slot_read' from incompatible pointer type
sbd.c:452: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c:453: error: dereferencing pointer to incomplete type
sbd.c: In function 'slot_unused':
sbd.c:473: error: dereferencing pointer to incomplete type
sbd.c:474: warning: passing argument 2 of 'slot_read' from incompatible pointer type
sbd.c:477: error: dereferencing pointer to incomplete type
sbd.c: In function 'slot_allocate':
sbd.c:518: error: dereferencing pointer to incomplete type
sbd.c:519: error: dereferencing pointer to incomplete type
sbd.c:520: error: dereferencing pointer to incomplete type
sbd.c:520: error: dereferencing pointer to incomplete type
sbd.c:521: warning: passing argument 2 of 'slot_write' from incompatible pointer type
sbd.c: In function 'slot_list':
sbd.c:554: error: dereferencing pointer to incomplete type
sbd.c:555: warning: passing argument 2 of 'slot_read' from incompatible pointer type
sbd.c:558: error: dereferencing pointer to incomplete type
sbd.c:559: warning: passing argument 2 of 'mbox_read' from incompatible pointer type
sbd.c:563: error: dereferencing pointer to incomplete type
sbd.c:563: error: dereferencing pointer to incomplete type
sbd.c:564: error: dereferencing pointer to incomplete type
sbd.c: In function 'slot_msg':
sbd.c:604: error: dereferencing pointer to incomplete type
sbd.c:605: error: dereferencing pointer to incomplete type
sbd.c:610: error: dereferencing pointer to incomplete type
sbd.c:610: error: dereferencing pointer to incomplete type
sbd.c:614: warning: passing argument 2 of 'mbox_write_verify' from incompatible pointer type
sbd.c: In function 'daemonize':
sbd.c:709: warning: passing argument 2 of 'mbox_write' from incompatible pointer type
sbd.c:719: warning: passing argument 2 of 'mbox_read' from incompatible pointer type
sbd.c:724: error: dereferencing pointer to incomplete type
sbd.c:726: error: dereferencing pointer to incomplete type
sbd.c:726: error: dereferencing pointer to incomplete type
sbd.c:728: error: dereferencing pointer to incomplete type
sbd.c:729: error: 'SBD_MSG_TEST' undeclared (first use in this function)
sbd.c:730: error: dereferencing pointer to incomplete type
sbd.c:731: warning: passing argument 2 of 'mbox_write' from incompatible pointer type
sbd.c:733: error: 'SBD_MSG_RESET' undeclared (first use in this function)
sbd.c:736: error: 'SBD_MSG_OFF' undeclared (first use in this function)
sbd.c:739: error: 'SBD_MSG_EXIT' undeclared (first use in this function)
sbd.c: In function 'header_dump':
sbd.c:768: error: dereferencing pointer to incomplete type
sbd.c:769: error: dereferencing pointer to incomplete type
sbd.c:771: error: dereferencing pointer to incomplete type
sbd.c:773: error: dereferencing pointer to incomplete type
sbd.c:775: error: dereferencing pointer to incomplete type
sbd.c:777: error: dereferencing pointer to incomplete type
sbd.c:779: error: dereferencing pointer to incomplete type
make[2]: *** [sbd-sbd.o] Error 1
make[2]: Leaving directory `/home/horms/projects/linux-ha/debian/sid/heartbeat-2.1.4/heartbeat-2.1.4/lib/stonith'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/horms/projects/linux-ha/debian/sid/heartbeat-2.1.4/heartbeat-2.1.4/lib'
make: *** [all-recursive] Error 1

Signed-off-by: Simon Horman <horms@verge.net.au>